#!/bin/bash

__LOGLEVEL=5

# Required for each site to be backed up:
# 
#    Add site name to sites
#    Add database name to databaseNames
#    Add document root path to docRootPaths
#        Double check sites against databaseNames and docRoots

#This needs to be added to logrotate
logFilePath=/var/log/backupadmin/scriptedBackup.log

exec 1>>${logFilePath}
exec 2>>${logFilePath}

declare -A logNameToLevel
logNameToLevel=([crit]="1" [error]="2" [warn]="3" [info]="4" [debug]="5")

function .log () {
    local levelName=${1};
    local level=${logNameToLevel[${levelName}]};

    # this moves the parameter numbers
    shift;

    if [[ ${__LOGLEVEL} -ge ${level} ]]; then
        echo -e "[${levelName}]" "$@";
    fi;
}

scriptName="$(basename $0)"
timeStamp=$(date +%Y%m%0d-%H:%M:%S)
.log crit "***Starting ${scriptName}***"
.log crit "${timeStamp}"

mysqlPasswordFilePath="/home/webadmin/scripts/webserverBackups/.tempsql"

destDir="/home/backupadmin/backups/"
.log info "Destination directory: ${destDir}"

httpdConfigDir="/etc/httpd/"

tarFileExtension=".tar"
gzipTarFileExtension=".tar.gz"

stagingDir="/home/webadmin/backupStaging/"

curDate=$(date +%Y%m%0d)

sites=(amm fft ltr)
.log debug "Sites we know about: ${sites[@]}"

declare -A databaseNames
declare -A docRootPaths

databaseNames=([amm]="ammwp" [fft]="fftwp" [ltr]="ltrwp" [mam]="mamwp")
docRootPaths=([amm]="/var/www/html/adventistmediaministries.com/" [fft]="/var/www/html/faithfortoday.tv" [ltr]="/var/www/html/lifetalk.net" [mam]="/var/www/html/madaboutmarriage.com")

for i in ${sites[@]}; do
    .log debug "Parameter received in for loop";
    siteName=${i};
    databaseName=${databaseNames[${siteName}]};
    docRootPath=${docRootPaths[${siteName}]};
    dumpFileName="${databaseName}DBdump_${siteName}_${curDate}.sql";
    mysqlDBdumpFileName="mysqlDBdump_${siteName}_${curDate}.sql";
    destFileName="${siteName}_backup"

    tarFileNamePath="${destDir}${destFileName}${tarFileExtension}";
    destFileNamePath="${destDir}${destFileName}${gzipTarFileExtension}"

    dumpFileNamePath="${stagingDir}${dumpFileName}"
    mysqlDBdumpFileNamePath="${stagingDir}${mysqlDBdumpFileName}"

    .log info "Beginning backup of ${siteName}";
    .log debug "Document Root path: ${docRootPath}";
    .log debug "Database name: ${databaseName}";
    .log debug "Temporary database dump file: ${dumpFileNamePath}";
    .log debug "Temporary mysql database dump file: ${mysqlDBdumpFileNamePath}";

    .log debug "Beginning mysqldump of database ${databaseName}";
    mysqldump --defaults-extra-file=${mysqlPasswordFilePath} --add-drop-table ${databaseName} > ${dumpFileNamePath}

    .log debug "Beginning mysqldump of database mysql";
    mysqldump --defaults-extra-file=${mysqlPasswordFilePath} --add-drop-table mysql > ${mysqlDBdumpFileNamePath}

    .log debug "Confirm contents of staging directory";
    .log debug "$(ls -lh ${stagingDir})";

    if [[ -e ${dumpFileNamePath} ]]; then
        .log debug "tar'ing of ${stagingDir}${dumpFileName} and ${stagingDir}${mysqlDBdumpFileName}";
        tar -cf ${tarFileNamePath} -C ${stagingDir} ${dumpFileName} ${mysqlDBdumpFileName} 2>&1 | grep -v "tar: Removing leading";

        .log debug "tar'ing append of ${httpdConfigDir}";
        tar --exclude=run --exclude=logs --exclude=modules -rf ${tarFileNamePath} ${httpdConfigDir} 2>&1 | grep -v "tar: Removing leading";

        .log debug "tar'ing append of ${docRootPath}";
        tar -rf ${tarFileNamePath} ${docRootPath} 2>&1 | grep -v "tar: Removing leading";
        
        .log debug "zip'ing of ${tarFileNamePath}";
        # this alters the file name
        gzip -f ${tarFileNamePath};

        .log info "Destination file: ${destFileNamePath}";

        md5=$(md5sum ${destFileNamePath} | awk '{ print $1 }');
        .log info "Destination file md5: ${md5}";

    else
        #echo "Something went wrong. There is no .sql dump file in ${stagingDir}";
        .log crit "Something went wrong. There is no .sql dump file in ${stagingDir}";
    fi

    if [[ -e ${destFileNamePath} ]]; then
        .log debug "Removing temp files";
        #echo "Removing temp files";
        rm "${dumpFileNamePath}";
    
        rm "${mysqlDBdumpFileNamePath}";
    fi
done
.log info "$(echo "Final contents of ${destDir}"; ls -lh ${destDir} | grep -v "total")"

.log crit "***Reached end of ${scriptName}***"
